src/Interne/StructureBundle/Entity/Groupe.php
<?php

namespace Interne\StructureBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Interne\StructureBundle\Entity\Type;

/**
 * Groupe
 *
 * @ORM\Table(name="structure_groupes")
 * @ORM\Entity(repositoryClass="Interne\StructureBundle\Entity\GroupeRepository")
 */
class Groupe
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var Groupe
     * @ORM\ManyToOne(targetEntity="Interne\StructureBundle\Entity\Groupe", inversedBy="enfants")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     */
    private $parent;

    /**
     * @var ArrayCollection 
     * @ORM\OneToMany(targetEntity="Interne\StructureBundle\Entity\Groupe", mappedBy="parent")
     */
    private $enfants;

	/**      
	 * @var ArrayCollection 
     * 
     * @ORM\OneToMany(targetEntity="Attribution", mappedBy="groupe", cascade={"persist"})
     */
    private $attributions;

    /**
     * @var Type $type
     * 
     * @ORM\ManyToOne(targetEntity="Type", inversedBy="groupes", cascade={"persist"})
     */
    private $type;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->enfants = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Groupe
     */
    public function setNom($nom)
    {
        $this->nom = ucwords($nom);
    
        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return ucwords($this->nom);
    }

    /**
     * Set parent
     *
     * @param \stdClass $parent
     * @return Groupe
     */
    public function setParent($parent)
    {
        $this->parent = $parent;
    
        return $this;
    }

    /**
     * Get parent
     *
     * @return \stdClass 
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Set enfants
     *
     * @param array $enfants
     * @return Groupe
     */
    public function setEnfants($enfants)
    {
        $this->enfants = $enfants;
    
        return $this;
    }

    /**
     * Get enfants
     *
     * @return array 
     */
    public function getEnfants()
    {
        return $this->enfants;
    }
    
    /**
     * Add enfants
     *
     * @param \Interne\StructureBundle\Entity\Groupe $enfants
     * @return Groupe
     */
    public function addEnfant(\Interne\StructureBundle\Entity\Groupe $enfants)
    {
        $this->enfants[] = $enfants;
    
        return $this;
    }

    /**
     * Remove enfants
     *
     * @param \Interne\StructureBundle\Entity\Groupe $enfants
     */
    public function removeEnfant(\Interne\StructureBundle\Entity\Groupe $enfants)
    {
        $this->enfants->removeElement($enfants);
    }

    /**
     * Add attributions
     *
     * @param \Interne\StructureBundle\Entity\Attribution $attributions
     * @return Groupe
     */
    public function addAttribution(\Interne\StructureBundle\Entity\Attribution $attributions)
    {
        $this->attributions[] = $attributions;
    
        return $this;
    }

    /**
     * Remove attributions
     *
     * @param \Interne\StructureBundle\Entity\Attribution $attributions
     */
    public function removeAttribution(\Interne\StructureBundle\Entity\Attribution $attributions)
    {
        $this->attributions->removeElement($attributions);
    }

    /**
     * Get attributions
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAttributions()
    {
        return $this->attributions;
    }

    /**
     * Set type
     *
     * @param \Interne\StructureBundle\Entity\Type $type
     * @return Groupe
     */
    public function setType(\Interne\StructureBundle\Entity\Type $type = null)
    {
        $this->type = $type;
	    $type->addGroupe($this);
        return $this;
    }

    /**
     * Get type
     *
     * @return \Interne\StructureBundle\Entity\Type 
     */
    public function getType()
    {
        return $this->type;
    }

    public function getMembers()
    {

        $members = array();
        $today   = new \Datetime();

        foreach ($this->getAttributions() as $attribution) {
            if ($attribution->getDateFin() == null || $attribution->getDateFin() > $today)
                array_push($members, $attribution->getMembre());

        }

        return $members;

    }

    public function getMembersRecursive()
    {

        $members = $this->getMembers();

        foreach ($this->getEnfants() as $childGroup) {
            $members = array_merge($members, $childGroup->getMembersRecursive());
        }

        return $members;
    }
}

src/Interne/StructureBundle/Controller/StructureController.php
<?php

namespace Interne\StructureBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

use Interne\StructureBundle\Entity\Groupe;
use Interne\StructureBundle\Entity\Type;
use Interne\StructureBundle\Form\GroupeType;
use Interne\StructureBundle\Form\TypeType;

class StructureController extends Controller
{
	
	/**
	 * Offre la vue de la hierarchie du groupe, ainsi que les divers options, comme
	 * ajouter un groupe enfant à un autre groupe etc...
	 */
	
    public function hierarchieAction()
    {
        $em = $this->getDoctrine()->getManager();

    	$groupe  = new Groupe();
        $em->persist($groupe);
        $form 	 = $this->createForm(new GroupeType, $groupe);

        //On récupère aussi le formulaire de type
        $type = new Type();
        $em->persist($type);
        $typeForm = $this->createForm(new TypeType, $type);

        return $this->render('InterneStructureBundle:Structure:hierarchie.html.twig', array(
	    
	    'groupeForm'	=> $form->createView(),
	    'typeForm'		=> $typeForm->createView()
        ));
    }
    
    /**
     * permet d'ajouter un groupe
     */
    public function addGroupeAction() {

        $groupe  = new Groupe();
        $form 	 = $this->createForm(new GroupeType, $groupe);
        $em      = $this->getDoctrine()->getManager();
        $session = new Session();

        //On valide un éventuel formulaire d'ajout de groupe
        if ($this->getRequest()->isMethod('POST')) {

            $form->bind($this->getRequest());

            if ($form->isValid()) {

                //On persiste le nouveau groupe
                $persistor = $this->get('global.persistor');
                $persistor->safePersist($groupe);

                //$em->persist($groupe);
                $em->flush();

                if($persistor->hasValidatorRoles())
                    $session->getFlashBag()->add('notice', 'Groupe ajouté avec succès');
                else
                    $session->getFlashBag()->add('notice', "Une demande d'ajout de groupe a été envoyée");
            }

            else
                $session->getFlashBag()->add('error', 'Erreur lors du traitement des données');
        }

        return $this->redirect($this->generateUrl('InterneStructure_hierarchie'));
    }
    
    /**
     * permet d'ajouter un type de groupe
     */
    public function addTypeAction() {
	
	$em      = $this->getDoctrine()->getManager();
	$session = new Session();
	
	//On récupère aussi le formulaire de type
	$type = new Type();
	$typeForm = $this->createForm(new TypeType, $type);
	
	if ($this->getRequest()->isMethod('POST')) {
		
		$typeForm->bind($this->getRequest());
		
		
		if($typeForm->isValid() ) {

		    $em->persist($type);
		    $em->flush();
		    $session->getFlashBag()->add('notice', 'Type ajouté avec succès');
		}
		
		else
		    $session->getFlashBag()->add('error', 'Erreur lors du traitement des données');
	}
	
	return $this->redirect($this->generateUrl('InterneStructure_hierarchie'));
    }
    
    /**
     * La méthode AJAXgetFullHierarchieAction retourne la hierarchie complète du groupe pour
     * affichage, vu que l'action de récupération est longue, on fait ca en ajax
     */
    public function AJAXGetFullHierarchieAction() {
    	
    	
    	$em 		= $this->getDoctrine()->getManager();
    	$repo 		= $em->getRepository('InterneStructureBundle:Groupe');
	$main		= $repo->findMainParent()[0];
	
	return new JsonResponse(array(
	    
	    'icon' 	=> '/netBS/web/static/images/layout/group.png',
	    'text'	=> $main->getNom(),
	    'children'	=> $repo->findJsonHierarchie($main),
	    'li_attr'	=> array('groupe_id' => $main->getId()),
	    'state'	=> array('opened' => true)
	));
    }
    
    /**
     * Permet d'afficher un groupe, ses informations etc.
     */
    public function voirGroupeAction($id) {
    	
    	$em     	= $this->getDoctrine()->getManager();
    	$gRepo    	= $em->getRepository('InterneStructureBundle:Groupe');
    	$groupe 	= $gRepo->find($id);
    	
    	//On récupère les attributions liées à ce groupe
    	$aRepo		= $em->getRepository('InterneStructureBundle:Attribution');
	
        $troupe = false;

        //Si le groupe en question est un troupe
        //alors on affiche la barre d'action spéciale troupe
        if($groupe->getType() != null && strtolower($groupe->getType()->getNom()) == 'troupe') {

            $troupe = true;
        }

    	//On récupère également l'ensemble des attributions liées à ce groupe pour afficher
    	//les membres courants, donc également trouver les membres des groupes enfants possibles
        $attrs		= $aRepo->findCurrentAttributionsForThisGroupe($groupe);

    	return $this->render('InterneStructureBundle:Structure:voir_groupe.html.twig', array(
    		
    		'groupe'		=> $groupe,
    		'attrs'			=> $attrs,
		    'isTroupe'		=> $troupe
    	));
    }
    
}

src/Interne/StructureBundle/Resources/views/Structure/attributions_fonctions.html.twig
{% extends "InterneHomeBundle::layout.html.twig" %}

{% block title %}Attributions{% endblock %}


{% block body %}
	
	<div class="row">
		<div class="col-md-4">
			<div class="widget">
				<div class="widget-title">
					<span>Fonctions</span>
				</div>
				<div class="widget-content">
					
					<table class="datatable">
						<thead>
							<tr>
								<th>nom</th>
								<th>abreviation</th>
								<th>droits</th>
								<th>options</th>
							</tr>
						</thead>
						
						<tbody>
						
							{% for fonction in fonctions %}
							
								<tr>
									<td>{{ fonction.nom }}</td>
									<td>{{ fonction.abreviation | upper }}</td>
									<td></td>
									<td></td>
								</tr>
							
							{% endfor %}
							
							
						</tbody>
						
					</table>
					
				</div>
			</div>
		</div>
		
		<div class="col-md-8">
			<div class="widget">
				<div class="widget-title">
					<span>Attributions existantes</span>
					<div class="widget-toolbar">
						<button class="widget-options-button">Recherche avancée</button>
					</div>
				</div>
				<div class="widget-content">
					
					<div class="widget-options field">
					
						<h4>Rechercher des attributions</h4>
						
						{{ form_widget(groupeList.groupe) }}
							
						<select id="hierarchie">
							<option value="main">Ce groupe uniquement</option>
							<option value="children">Ses enfants uniquement</option>
							<option value="all">Ce groupe et ses enfants</option>
						</select>
						
						<input id="date1" class="datepicker" placeholder="Début" />
						<input id="date2" class="datepicker" placeholder="Fin" />
						
						<button onclick="retrieveAttributions(null, this);">Rechercher</button>
					
					</div>
					
					<table class="datatable datatable-membre" id="attributionsTable">
							
						<thead>
							<tr>
								<th></th>
								<th>nom</th>
								<th>prenom</th>
								<th>fonction</th>
								<th>groupe</th>
								<th>debut</th>
								<th>fin</th>
							</tr>
						</thead>
						
						<tbody>
						
							
						</tbody>
						
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}
	<script type="text/javascript" src="{{ asset('static/js/groupes.js') }}"></script>
{% endblock %}

src/Interne/StructureBundle/Resources/views/Structure/distinctions.html.twig
{% extends "InterneHomeBundle::layout.html.twig" %}

{% block title %}Distinctions{% endblock %}


{% block body %}

	<div class="row">
		<div class="col-md-12">
			<div class="widget">
				<div class="widget-title">
					<span>Distinctions</span>
					<div  class="widget-toolbar">
						<button data-toggle="modal" data-target="#distinctionModal">Ajouter</button>
					</div>
				</div>
				<div class="widget-content">
					<table class="datatable">
						<thead>
							<tr>
								<th>nom</th>
								<th>droits</th>
								<th>remarques</th>
								<th>options</th>
							</tr>
						</thead>
						
						<tbody>
						
							{% for distinction in distinctions %}
							
								<tr>
									<td>{{ distinction.nom }}</td>
									<td></td>
									<td>{{ distinction.remarques }}</td>
									<td></td>
								</tr>
							
							{% endfor %}
							
							
						</tbody>
						
					</table>
				</div>
			</div>
		</div>
	</div>
	
<div class="modal fade" id="distinctionModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
				<h4 class="modal-title" id="myModalLabel">Ajouter une distinction</h4>
			</div>
			<div class="modal-body">
			
				<form method="post" id="distinction-form">
					
					{{ form_errors(distinctionForm)}}
					<fieldset>
						<div class="row">
							<div class="col-sm-4">{{ form_label(distinctionForm.nom, "Nom") }}</div>
							<div class="col-sm-8">{{ form_widget(distinctionForm.nom) }}</div>
						</div>
						
						<div class="row">
							<div class="col-sm-4">{{ form_label(distinctionForm.remarques, "Remarques") }}</div>
							<div class="col-sm-8">{{ form_widget(distinctionForm.remarques) }}</div>
						</div>
					</fieldset>
					
					{{ form_rest(distinctionForm) }}
					
				</form>
			
			</div>
			
			<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			<button type="button" onclick="document.getElementById('distinction-form').submit();" class="btn btn-primary">Ajouter</button>
			</div>
		</div>
	</div>
</div>

{% endblock %}

src/Interne/StructureBundle/Resources/views/Structure/hierarchie.html.twig
{% extends "InterneHomeBundle::layout.html.twig" %}

{% block title %}Hierarchie{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('static/css/jstree.css') }}">
	<link rel="stylesheet" href="{{ asset('static/css/hierarchie.css') }}">
{% endblock %}



{% block body %}


    <div class="row">

        <div class="col-lg-6">
            <div class="widget">
			<div class="widget-title">
				<span>Hierarchie complète</span>
				
				<div class="widget-toolbar">

                <button onclick="retrieveHierarchie();">Récupérer</button>
				</div>
			</div>
			
			<div class="widget-content">
				<div style="padding:20px;" id="hierarchie"></div>
			</div>
		</div>
	</div>

        <div class="col-lg-6">

        <div class="row">
			
			<div class="col-lg-12">
			
				<div class="widget">
					<div class="widget-title">
						<span>Ajouter un groupe</span>
					</div>
					
					<div class="widget-content">
						<form method="post" action="{{ path('InterneStructure_ajouter_groupe') }}">
							
							{% include 'InterneStructureBundle:Form:groupe_form.html.twig' %}
							
						</form>
					</div>
				</div>
				
			</div>
		
		</div>
		
		<div class="row">
			
			<div class="col-lg-12">
			
				<div class="widget">
					<div class="widget-title">
						<span>Ajouter un type de groupe</span>
					</div>
					
					<div class="widget-content">
						<form method="post" action="{{ path('InterneStructure_ajouter_type') }}">
							
							{% include 'InterneStructureBundle:Form:type_form.html.twig' %}
							
						</form>
					</div>
				</div>
				
			</div>
		
		</div>
		
	</div>
	
</div>


{% endblock %}

{% block javascript %}

	<script type="text/javascript" src="{{ asset('static/js/jstree.js') }}"></script>
	<script type="text/javascript" src="{{ asset('static/js/groupes.js') }}"></script>


    <script>
        $(function () {
            retrieveHierarchie();
        });
    </script>

{% endblock %}

src/Interne/StructureBundle/Resources/views/Structure/listeMembresGeneric.html.twig
<div class="widget">

    <div class="widget-title">
        <span>Effectifs - {{ nomGroupe }}</span>

        <div class="widget-toolbar">

            <button class="widget-options-button">Recherche</button>
        </div>
    </div>

    <div class="widget-content">

        <div class="widget-options field">

            <h4>Rechercher des membres liés</h4>

            <select id="hierarchie">
                <option value="main">Ce groupe uniquement</option>
                <option value="all">Ce groupe et ses enfants</option>
                <option value="children">Ses enfants uniquement</option>
            </select>

            <input placeholder="Début" type="text" id="date1" class="datepicker"/>
            <input placeholder="Fin" type="text" id="date2" class="datepicker"/>

            <button class="btn btn-primary" onclick="retrieveAttributions({{ groupe.id }}, this);">Valider</button>

            <p><strong>Astuce :</strong> Laisser les deux champs de date vide retournera la liste de toutes les
                attributions (Peut prendre du temps)</p>

        </div>

        <table id="membersTable" class="datatable  datatable-membre">

            <thead>
            <tr>
                <th></th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Date de naissance</th>
                <th>Fonction</th>
                <th>A {{ nomGroupe }} depuis</th>
                <th>Options</th>

            </tr>
            </thead>

            <tbody>

            {% for attribution in attrs %}

                <tr>
                    <td><input type="checkbox" id="membre_{{ attribution.membre.id }}"/></td>

                    <td><a href="{{ path('InterneFichier_voir_membre', {'id' : attribution.membre.id}) }}">{{ attribution.membre.prenom }}</a>
                    <td>{{ attribution.membre.famille.nom }}</td>
                    <td>{{ attribution. membre.naissance|date('d.m.Y') }}</td>
                    <td>{{ attribution.fonction.nom }}</td>
                    <td>{{ attribution.dateDebut|date("d.m.Y") }}</td>


                    <td>
                        <a class="btn btn-xs btn-primary" onclick="persistList({{ attribution.membre.id }});"><span class="glyphicon glyphicon-list"></span></a>
                        <a class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
                    </td>

                </tr>

            {% endfor %}

            </tbody>

        </table>

    </div>

</div>

src/Interne/StructureBundle/Resources/views/Structure/voir_groupe.html.twig
{% extends "InterneHomeBundle::layout.html.twig" %}

{% block title %}{{ groupe.nom }}{% endblock %}


{% block body %}

	<div class="row">
		
		<div class="col-lg-6 col-lg-offset-1">

        <h2>{{ groupe.nom }}</h2>
			
		</div>
    </div>

    <div class="row">
        <div class="col-lg-10">

            <div class="row">

                <div class="col-lg-2">

                    <div class="widget">
                        <div class="widget-title">
                            <span>Groupe parent</span>
                        </div>

                        <div class="widget-content">

                            <div class="flex groupe-container">

                                {% if groupe.parent != null %}

                                    <a class="groupe"
                                       href="{{ path('InterneStructure_voir_groupe', {id: groupe.parent.id}) }}">
                                        {{ groupe.parent.nom }}
                                    </a>

                                {% endif %}

                            </div>

                        </div>
                    </div>

                </div>

                <div class="col-lg-10">
                    <div class="widget">
                        <div class="widget-title">
                            <span>Groupes enfants</span>
                        </div>

                        <div class="widget-content">

                            <div class="groupe-container flex">

                                {% for enfant in groupe.enfants %}

                                    <a class="groupe"
                                       href="{{ path('InterneStructure_voir_groupe', {id: enfant.id}) }}">
                                        {{ enfant.nom }}
                                    </a>

                                    <span class="glyphicon glyphicon-chevron-right"></span>

                                {% endfor %}

                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col-lg-12">

                    {{ include('InterneStructureBundle:Structure:listeMembresGeneric.html.twig', {'attributions' : attrs, 'nomGroupe': groupe.nom}) }}

                </div>

            </div>
        </div>

        <div class="col-lg-2">

            <h4>Effectifs</h4>
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="badge">{{ groupe.membersRecursive|length }}</span>
                    {{ groupe.nom }}
                </li>

                {% for groupeEnfant in groupe.enfants %}
                    <li class="list-group-item">
                        <span class="badge">{{ groupeEnfant.membersRecursive|length }}</span>
                        {{ groupeEnfant.nom }}
                    </li>
                {% endfor %}
            </ul>

            <h4>Outils</h4>

            <div id="title-toolbar">

                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        Exporter une liste <span class="caret"></span>
                    </button>

                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">PDF</a></li>
                        <li><a href="#">Excel</a></li>
                        <li><a href="#">Etiquettes</a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

{% block javascript %}

	<script type="text/javascript" src="{{ asset('static/js/groupes.js') }}"></script>

{% endblock %}